import type { Namespace } from "../index";

/** Неймспейс «muse» — ИИ-соавтор Cosmos. Ключи одинаковы во всех трёх языках; `mode.<id>` — название режима, `needs.<id>` — подсказка, когда текста нет. */
const muse: Namespace = {
  ru: {
    "mode.draft": "Набросок → пост", "needs.draft": "Напишите тему или пару слов — Cosmos развернёт их в пост.",
    "mode.polish": "Отполировать", "needs.polish": "Вставьте текст, который хотите улучшить.",
    "mode.hashtags": "Хэштеги", "needs.hashtags": "Нужен текст поста, чтобы подобрать теги.",
    "mode.translate": "Перевести", "needs.translate": "Нужен текст для перевода.",
    "mode.caption": "Подпись к медиа", "needs.caption": "Опишите фото или видео парой слов — Cosmos придумает подпись.",
    subtitle: "· ИИ-соавтор", thinking: "Cosmos думает…", suggest: "Предложить варианты",
    byClaude: "Сгенерировано Claude · вызов идёт с сервера",
    offline: "Офлайн-режим · {note}. Чтобы включить настоящий ИИ, добавьте ANTHROPIC_API_KEY в .env.local и перезапустите сервер.",
  },
  kk: {
    "mode.draft": "Нобай → жазба", "needs.draft": "Тақырыпты немесе бірер сөз жазыңыз — Cosmos оны жазбаға айналдырады.",
    "mode.polish": "Жылтырату", "needs.polish": "Жақсартқыңыз келген мәтінді қойыңыз.",
    "mode.hashtags": "Хэштегтер", "needs.hashtags": "Тегтерді таңдау үшін жазба мәтіні керек.",
    "mode.translate": "Аудару", "needs.translate": "Аудару үшін мәтін керек.",
    "mode.caption": "Медиаға қолтаңба", "needs.caption": "Фото немесе бейнені бірер сөзбен сипаттаңыз — Cosmos қолтаңба ойлап табады.",
    subtitle: "· ИИ-серіктес", thinking: "Cosmos ойланып жатыр…", suggest: "Нұсқаларды ұсыну",
    byClaude: "Claude жасады · сұраныс серверден жіберіледі",
    offline: "Офлайн режим · {note}. Нағыз ИИ-ді қосу үшін .env.local файлына ANTHROPIC_API_KEY қосып, серверді қайта іске қосыңыз.",
  },
  en: {
    "mode.draft": "Draft → post", "needs.draft": "Write a topic or a few words — Cosmos will turn them into a post.",
    "mode.polish": "Polish", "needs.polish": "Paste the text you want to improve.",
    "mode.hashtags": "Hashtags", "needs.hashtags": "Post text is needed to pick tags.",
    "mode.translate": "Translate", "needs.translate": "Text to translate is needed.",
    "mode.caption": "Media caption", "needs.caption": "Describe the photo or video in a few words — Cosmos will come up with a caption.",
    subtitle: "· AI co-author", thinking: "Cosmos is thinking…", suggest: "Suggest options",
    byClaude: "Generated by Claude · the call is made from the server",
    offline: "Offline mode · {note}. To enable the real AI, add ANTHROPIC_API_KEY to .env.local and restart the server.",
  },
};
export default muse;
